sudo: required
services:
  - docker

before_install:
  - docker build -t sadhman/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run sadhwanim/react-test npm test -- --coverage

after_success:
  - docker build -t sadhman/multi-client ./client
  - docker build -t sadhman/multi-server ./server
  - docker build -t sadhman/multi-worker ./worker
  - docker build -t sadhman/multi-nginx ./nginx

    #pushing to docker hub
    #login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #pushing images
  - docker push sadhman/multi-client
  - docker push sadhman/multi-server
  - docker push sadhman/multi-worker
  - docker push sadhman/multi-nginx
